apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.0.14
    helm:
      values: |
        image:
          repository: docker.io/bitnami/minio
          tag: latest
        mode: standalone
        rootUser: admin
        rootPassword: minio123
        persistence:
          enabled: false
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true