apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    image:
      tag: latest
    chart: minio
    targetRevision: 14.6.19
    helm:
      values: |
        auth:
          rootUser: admin
          rootPassword: minio123
        defaultBuckets: mlflow
        service:
          type: ClusterIP
        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true