apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.7.3
    helm:
      values: |
        service:
          type: ClusterIP
        auth:
          enabled: false

        # PostgreSQL backend
        backendStore:
          databaseMigration: true
          backendStoreUri: postgresql://mlflow:mlflow123@postgresql.mlflow.svc.cluster.local:5432/mlflow

        # MinIO artifact storage
        artifactRoot: s3://mlflow/
        extraEnvVars:
          - name: MLFLOW_S3_ENDPOINT_URL
            value: http://minio.mlflow.svc.cluster.local:9000
          - name: AWS_ACCESS_KEY_ID
            value: admin
          - name: AWS_SECRET_ACCESS_KEY
            value: minio123
          - name: AWS_DEFAULT_REGION
            value: us-east-1
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true