apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools    # same namespace where ArgoCD runs
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts    # <-- OCI endpoint
    chart: mlflow
    targetRevision: 5.1.21                     # version from ArtifactHub
    helm:
      values: |
        service:
          type: ClusterIP
        auth:
          enabled: false
        artifactRoot: /mlruns
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true