apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.8.0
    helm:
      values: |
        service:
          type: ClusterIP
        auth:
          enabled: false

        backendStore:
          database:
            type: postgres
            host: postgresql.mlflow.svc.cluster.local
            port: 5432
            user: mlflow
            password: mlflow123
            database: mlflow

        artifactRoot:
          type: s3
          s3:
            bucket: mlflow
            endpoint: http://minio.mlflow.svc.cluster.local:9000
            accessKey: admin
            secretKey: minio123
            secure: false

        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: http://minio.mlflow.svc.cluster.local:9000
          AWS_ACCESS_KEY_ID: admin
          AWS_SECRET_ACCESS_KEY: minio123
          AWS_DEFAULT_REGION: us-east-1
          PUSHGATEWAY_URL: http://pushgateway.mlflow.svc.cluster.local:9091

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true